Repository SpikeInterface/MEArec, pull requests merged in 2023-09, with the labels that each got.

#159 Improve Docs I
  docs/generate_recordings.rst
  docs/generate_templates.rst
  docs/installation.rst
  docs/overview.rst
Labels: documentation

#163 Do not remove resampled templates if not resampled
  src/MEArec/default_params/templates_params.yaml
  src/MEArec/generators/recordinggenerator.py
Labels: enhancement

#162 Fix numpy deprecations
  src/MEArec/cli.py
  src/MEArec/simulate_cells.py
Labels: deprecations
